### ISSUE TITLE
Setup documentation with MKDocs

### ISSUE THREAD

**Issue by JohnGiorgi** [BaderLab/saber#10]
Need some documentation other than the [MKDocs](https://www.mkdocs.org)

**TODO**

- [x] Setup a simple page with [MKDocs](https://www.mkdocs.org)
- [x] Choose a nice theme!
- [x] Find someone elses documentation to use as inspiration (maybe [Keras](https://keras.io)?)
- [x] "Sync" information across the readme, documentation, and notebook.
