### ISSUE TITLE
Some methods should allow arguments

### ISSUE THREAD

**Issue by JohnGiorgi** [BaderLab/Saber#30]
Some methods, such as `SequenceProcessor.load_dataset()` and `SequenceProcessor.load_embeddings()` should allow the user to specify filepaths. Otherwise, using saber as a python library is pretty useless, as you have to set these files in the `config.ini` file everytime. 

Arguments passed to these methods should update the `Config` object

**TODO**

- [x] Add filepath argument to `SequenceProcessor.load_dataset()` and `SequenceProcessor.load_embeddings()` (really, any method that operates on a filepath)
- [x] These arguments should update the corresponding values in `config` instance.
- [x] Config that updating `config` attributes works as expected.
